// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCccb1pNLc9CdsJZ9AxUHOYFeQPLZZSw3Y',
    appId: '1:861380003065:web:3c362b91233dea40578e28',
    messagingSenderId: '861380003065',
    projectId: 'rxvision-5c8a8',
    authDomain: 'rxvision-5c8a8.firebaseapp.com',
    storageBucket: 'rxvision-5c8a8.firebasestorage.app',
    measurementId: 'G-PPMPE9H5MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhB5F7pa5OC5zfYNIohFf0Rzyqqg5IojI',
    appId: '1:861380003065:android:6d9755a679dadba4578e28',
    messagingSenderId: '861380003065',
    projectId: 'rxvision-5c8a8',
    storageBucket: 'rxvision-5c8a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa3-oPdN19IFWgTlcxDSbJoJdR2lMZKxI',
    appId: '1:861380003065:ios:37557b4c8333877a578e28',
    messagingSenderId: '861380003065',
    projectId: 'rxvision-5c8a8',
    storageBucket: 'rxvision-5c8a8.firebasestorage.app',
    iosBundleId: 'com.example.rxvisionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa3-oPdN19IFWgTlcxDSbJoJdR2lMZKxI',
    appId: '1:861380003065:ios:37557b4c8333877a578e28',
    messagingSenderId: '861380003065',
    projectId: 'rxvision-5c8a8',
    storageBucket: 'rxvision-5c8a8.firebasestorage.app',
    iosBundleId: 'com.example.rxvisionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCccb1pNLc9CdsJZ9AxUHOYFeQPLZZSw3Y',
    appId: '1:861380003065:web:079edce0fef1b668578e28',
    messagingSenderId: '861380003065',
    projectId: 'rxvision-5c8a8',
    authDomain: 'rxvision-5c8a8.firebaseapp.com',
    storageBucket: 'rxvision-5c8a8.firebasestorage.app',
    measurementId: 'G-R2YX6Z0RJR',
  );
}
